# Generated by Django 4.2.2 on 2024-05-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pag', '0002_auto_20240512_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='teléfono',
            new_name='telefono',
        ),
    ]
