# Generated by Django 4.2.2 on 2024-05-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pag', '0003_rename_teléfono_proveedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='nombre_preg',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(max_length=40),
        ),
    ]
