# Generated by Django 4.2.2 on 2024-05-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pag', '0004_alter_pregunta_nombre_preg_alter_rol_nombre_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='nombre_preg',
            field=models.CharField(max_length=50),
        ),
    ]
